### ISSUE TITLE
Unable to launch Docker for Windows

### ISSUE THREAD

**Issue by rizahmed1** [docker/toolbox#731]
Unable to launch Docker for Windows
Hyper V is already enabled

Unable to create: You cannot call a method on a null-valued expression.
at <ScriptBlock>, <No file>: line 138
at Get-NetAdapter<End>, <No file>: line 181
at New-Switch, <No file>: line 138
at <ScriptBlock>, <No file>: line 409
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Please advise

**Comment by automatenv212** [comment]
can you provide more information on the environment. Like what windows you are on ?
and how are you trying to launch it ?
