### ISSUE TITLE
brew cask install docker-toolbox

### ISSUE THREAD

**Issue by LunarDevelopment** [docker/toolbox#870]
Hello! 

This may be better off in the brew cask repo, so apologies in advance! 

I'm getting the below error when running `$ brew cask install docker-toolbox`, I'm clueless to what is going wrong. 

OSX Catalina (latest) with latest docker for Mac app installed on system. 

```sh
$ brew cask install docker-toolbox
==> Downloading https://github.com/docker/toolbox/releases/download/v19.03.1/DockerToolbox-19.03.1.pkg
Already downloaded: /Users/lewis/Library/Caches/Homebrew/downloads/f4e3e5a3fadb8919628206bd7207861f8862278e1acff449e94c9965d8414b05--DockerToolbox-19.03.1.pkg
==> Verifying SHA-256 checksum for Cask 'docker-toolbox'.
==> Installing dependencies: virtualbox
==> Caveats
To install and/or use virtualbox you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Downloading https://download.virtualbox.org/virtualbox/6.1.0/VirtualBox-6.1.0-135406-OSX.dmg
Already downloaded: /Users/lewis/Library/Caches/Homebrew/downloads/d3700155a9ac5d3c28f736aebc70a1873313b30092a2213fd5dd48212e19ce08--VirtualBox-6.1.0-135406-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is Oracle VM VirtualBox
installer: choices changes file '/var/folders/bh/pjngbhvs6mb68bznhgl3l3qh0000gn/T/choices20200102-26484-lapik5.xml' applied
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “VirtualBox.pkg”.)
==> Purging files for version 6.1.0,135406 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=lewis USER=lewis USERNAME=lewis /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.1.0,135406/VirtualBox.pkg -target / -applyChoiceChangesXML /var/folders/bh/pjngbhvs6mb68bznhgl3l3qh0000gn/T/choices20200102-26484-lapik5.xml` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: choices changes file '/var/folders/bh/pjngbhvs6mb68bznhgl3l3qh0000gn/T/choices20200102-26484-lapik5.xml' applied
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “VirtualBox.pkg”.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:70:in `block in with_choices_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:67:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:364:in `block in cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:351:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:351:in `cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:253:in `satisfy_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:65:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by LunarDevelopment** [comment]
For anyone else's reference on this: 

[Legacy desktop solution. Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. We recommend updating to the newer applications, if possible.](https://docs.docker.com/toolbox/toolbox_install_mac/)
